name: meeting
recipe: drupal8
config:
  webroot: web
tooling:
  phplint:
    service: appserver
    cmd: vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
  behat:
    service: appserver
    cmd: vendor/bin/behat
